---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry
  namespace: nia-os
spec:
  encryptedData:
    .dockerconfigjson: AgB1EVnqX7ah9kHJpkYn+Ih5gUJ4Kr5bir6MwteOx859g+CBHnSvoENZm5pJEnaLwO/iwIK2xfUnwDxHxnAfJHgPN48Bc3O2lYIPZUudJINQqUocliSXwb4gQ+sFhoyqTK8GeGjLpo193dC51u2czUkfexzlHlgaRayD73wP0AbW7n8voz62+Pp1b5HiaUSn//YF7My5pWpDJK26rIcvwvA16+gjVQWr3iQNHEajqfxBwLZ1wUuwE8TJ9SyYqyHuIKmr1dz/TlTLqBo4941wy+dv//72a65tsIeg0adAHupf+J6H5wCRNPiG4J/k9xLwionfG/xjsobXBRVRFlbd6BhLEj7K+9l7xXJfqdGZRYosGQKsFhCf5FghKLB8CkHWEpjXaC+OPBIQ8fvzUfLXEVC8ZbUCd6F+9wl7lSGG+/Mk2vY8Px0dD6JZZi094SonBCXBaOVQfzTk2H4gUo1OXymBj2zAEEffgL4PT/sCrvTJb/5fMgbajMhublu8JAh2nTJ0l0UV2hoE5oxBamovYflyszYA5WopuSrFprAFxWknDCPduAzlCBfwK1abF4sp2mI0gnszWsRlyOT1aiTZgLlYTA37kvmyddfjkr+WbgngHfRYZtCgwnlee8TkNsz6vmePkPHbJV12SVzwGgM2wO/UaVTmhjQUfAqapxw1AFATosNlerG2WgQOjlkDuR8mwqrL5EuKXC+dq6HkwLLNY7RgqXf+BRuNZcUVxlhr7mV9oFgpYXZ68WTW9C4sYOc1f/MWoS4LwbRRoMQVVlg9KX6xMm0Z/b7J+m/nQSBe4Ob5iF7YlJwWTKHIMp5k9TZ2c7hj310xu9bnWkSxE5tnuMmZ6aMevxxManci4L975arli+l/Rz65JCi8zbkh0rlKAs/zngE=
  template:
    metadata:
      name: registry
      namespace: nia-os
    type: kubernetes.io/dockerconfigjson
