---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry
  namespace: nia-os
spec:
  encryptedData:
    .dockerconfigjson: AgCb/yrGJFGPpeAoBV6nHnStmeDJAm0DLOODRBPpABokGQ+NMlXjAVWxegy8nchicTuEtvEaeZEigwIx87mC1xedj89q/OqAzAvNtjRAJzhwPUFGfYvRItolUCbBIJDDgN4X7PlOsC+cjsCztIpQxvK/LZCvZKp6XTNXhdKEPOkNb/YWoYceai8mIFP8MjQlC11emhTp0/3H63GriWxprLVqE2NiB0jvcaS35idotX3zFCiCbMHHlHVVo1VddeAyrbZycmCz7dJeRj9vLo3BLG5Gp/ECsYO8xGqMRYPUESZ7W7SqXiT8NeYsHGmgyBcuHE5hfeW1Rp7Y6VA5jEGynn9+iL/vVvsxL/MZCAAOwL6VStV7Fjff5oUVcnJY12Bb6O1oFIopT+ppyGD13q5atIX+x8rAD+bQiPwGuy10HhuGZNfBvHeM7lg9WwlLRk9ITGDg/dm/v5m6owP3UI7ITXJBkj+IRCKHXJ5Lad+WSHRsAU2Iueb5bUNqe+iZlJwwUhZg+2tuo1ocRQpafrhXmW/I1Tclr18AyjdPhwQPKEraGsyub6NJHe8Ea1phozvBc7VQtnKdIJvPi6oqMLPwR/C01gpJtQzZSivmyE8GsHhUgpqOkO+cV/sbTYr1EVlVgFg1X14ifOAzjBxcNxMjFzms8pCmhW16NVncqSoAiNtTTCfYdIcJniZVqfn6aUVeiIb9LrJ9yg8umQl9DU1WFaVdRwHV5akXpIrTmXi0Ks0315YXLcr9K0kBuO6VaE8J0s96nMRdGDVYzZJE7KtxR7vPy7oCzXNngTdFhevhwRJP8Uzy2QNaf86hYK+nFcl3jvb/s/iz7TqeSIPVT298vnfuBhMumlRRnrW4wyublbruj7DJpxyBGYQQWn4FLidgxmiEl34=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      name: registry
      namespace: nia-os
    type: kubernetes.io/dockerconfigjson
