# Generated by Django 6.0 on 2025-12-25 16:37

import django.db.models.deletion
import encrypted_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="Name"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, max_length=512, null=True, verbose_name="Summary"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clusters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cluster",
                "verbose_name_plural": "Clusters",
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "hostname",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="Hostname"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="IP Address"
                    ),
                ),
                ("username", models.CharField(max_length=128, verbose_name="Username")),
                (
                    "password",
                    encrypted_fields.fields.EncryptedCharField(
                        max_length=256, verbose_name="Password"
                    ),
                ),
                ("port", models.PositiveIntegerField(default=22, verbose_name="Port")),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="infrastructure.cluster",
                        verbose_name="Cluster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node",
                "verbose_name_plural": "Nodes",
                "unique_together": {("cluster", "hostname")},
            },
        ),
    ]
