# Generated by Django 6.0 on 2025-12-25 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="node",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="cluster",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_cluster_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                fields=("hostname", "cluster"), name="unique_node_hostname_per_cluster"
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                fields=("ip_address", "cluster"),
                name="unique_node_ip_address_per_cluster",
            ),
        ),
    ]
