# Generated by Django 6.0 on 2025-12-26 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0002_alter_node_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="port",
            field=models.PositiveIntegerField(
                default=22,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
                verbose_name="Port",
            ),
        ),
    ]
