# Generated by Django 6.0 on 2025-12-27 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0003_alter_node_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="agent_key",
            field=models.UUIDField(
                default=uuid.uuid4, null=True, verbose_name="Agent Key"
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last Seen"),
        ),
        migrations.AddField(
            model_name="node",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("ONLINE", "Online"),
                    ("OFFLINE", "Offline"),
                ],
                default="UNKNOWN",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
