# Generated by Django 6.0 on 2025-12-27 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("infrastructure", "0006_alter_node_agent_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                ("cpu_percent", models.FloatField(verbose_name="CPU %")),
                ("ram_percent", models.FloatField(verbose_name="RAM %")),
                ("disk_percent", models.FloatField(verbose_name="Disk %")),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="infrastructure.node",
                        verbose_name="Node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrics",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["node", "-created"],
                        name="monitoring__node_id_018860_idx",
                    )
                ],
            },
        ),
    ]
