# Generated by Django 6.0 on 2025-12-27 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metric",
            name="updated",
        ),
    ]
